version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    command: celery -A project worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/code

  celery_beat:
    build:
      context: .
    command: celery -A project beat --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/code
