# Generated by Django 5.1 on 2024-09-16 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance-requests/'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance-requests/'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance-requests/'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='maintenance-requests/'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='moved_in',
            field=models.DateField(default=datetime.date(2024, 9, 16)),
        ),
    ]
