# Generated by Django 5.0 on 2024-09-30 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='invoice_id',
            new_name='invoice',
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='property',
            field=models.ForeignKey(limit_choices_to={'available': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='base.property'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
