# Generated by Django 5.1 on 2024-09-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_maintenancerequest_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='moved_in',
            field=models.DateField(auto_now_add=True),
        ),
    ]
