# Generated by Django 5.0 on 2024-09-30 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_transaction_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentinvoice',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='base.property'),
        ),
    ]
