# Generated by Django 5.1 on 2024-09-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_tenantprofile_moved_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='type',
            field=models.CharField(choices=[('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Structural', 'Structural'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
