# Generated by Django 5.0 on 2024-10-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_rentinvoice_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image3',
        ),
        migrations.AlterField(
            model_name='property',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='static/property_images/'),
        ),
    ]
