# Generated by Django 5.0 on 2024-10-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_property_image2_remove_property_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('success', 'Success'), ('fail', 'Fail')], default='fail', max_length=10),
        ),
    ]
