# Generated by Django 5.0 on 2024-10-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_transaction_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='static/maintenance-requests/'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='static/maintenance-requests/'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='static/maintenance-requests/'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static/maintenance-requests/'),
        ),
        migrations.AlterField(
            model_name='rentinvoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/invoices/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pics/'),
        ),
    ]
