# Generated by Django 5.1 on 2024-09-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_tenantprofile_billed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='last_billed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
